### ISSUE TITLE
[v2.0.1] text beginning with [ throws an error

### ISSUE THREAD

**Issue by aleclarson** [genoma/language-pug#35]
```
~/pug-cli/node_modules/pug-lexer/index.js:60
    throw err;
    ^

Error: test.pug:77:7
    75|       em this is inside 'em' tag <br/>
    76| 
  > 77|       [this is rendered as standalone text
--------------^
    78|       ##this too
    79|       "this too"
    80| 

unexpected text "[this"
    at makeError (~/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (~/pug-cli/node_modules/pug-lexer/index.js:59:15)
    at Lexer.fail (~/pug-cli/node_modules/pug-lexer/index.js:1441:10)
    at Lexer.advance (~/pug-cli/node_modules/pug-lexer/index.js:1501:15)
    at Lexer.callLexerFunction (~/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (~/pug-cli/node_modules/pug-lexer/index.js:1512:12)
    at lex (~/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (~/pug-cli/node_modules/pug/lib/index.js:99:27)
    at Function.loadString [as string] (~/pug-cli/node_modules/pug-load/index.js:44:24)
    at compileBody (~/pug-cli/node_modules/pug/lib/index.js:86:18)
```

**Comment by aleclarson** [comment]
This is likely an error with Pug 2, so `language-pug` needs no changes.

```
~/pug-cli/node_modules/pug-lexer/index.js:60
    throw err;
    ^

Error: test.pug:78:7
    76| 
    77|       this is rendered as standalone text
  > 78|       "this too"
--------------^
    79| 
    80|     div(style="background-color: #eef") some examples of dot text blocks bellow:
    81| 

unexpected text ""this"
    at makeError (~/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (~/pug-cli/node_modules/pug-lexer/index.js:59:15)
    at Lexer.fail (~/pug-cli/node_modules/pug-lexer/index.js:1441:10)
    at Lexer.advance (~/pug-cli/node_modules/pug-lexer/index.js:1501:15)
    at Lexer.callLexerFunction (~/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (~/pug-cli/node_modules/pug-lexer/index.js:1512:12)
    at lex (~/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (~/pug-cli/node_modules/pug/lib/index.js:99:27)
    at Function.loadString [as string] (~/pug-cli/node_modules/pug-load/index.js:44:24)
    at compileBody (~/pug-cli/node_modules/pug/lib/index.js:86:18)
```
